events {}

http {
  server {
    listen 8000;

    location /rest/v1/ {
      rewrite ^/rest/v1/(.*)$ /$1 break;
      proxy_pass http://postgrest:3000;
      proxy_set_header Host $host;
      proxy_set_header Authorization $http_authorization;
      proxy_set_header apikey $http_apikey;
    }
  }
}
